import type { MiniGameDefinition, MiniGameType } from '../types/koko'

export const miniGameOrder: MiniGameType[] = ['catch', 'bubble', 'jumpRope', 'hideSeek']

export const miniGameDefinitions: Record<MiniGameType, MiniGameDefinition> = {
  catch: {
    game_id: 'catch',
    title: { en: 'Fetch Ball', zh: '接球游戏' },
    tabLabel: { en: 'Fetch', zh: '接球' },
    goal: { en: 'Fetch 4 balls before time runs out', zh: '倒计时内成功带回 4 次球' },
    startText: {
      en: 'Start the park link. Koko enters the M5StickS3 scene, then waits for your whistle signal.',
      zh: '启动公园联动后，Koko 会进入 M5StickS3 场景，然后等待你的口哨信号。',
    },
    runningText: {
      en: 'Tap Whistle when the timing bar reaches the green zone. The ball signal is thrown and Koko fetches it back.',
      zh: '观察口哨时机条，在绿色区域吹口哨；小球信号会同步抛出，Koko 会去捡回。',
    },
    successText: {
      en: 'Koko brought the ball back and looks very proud.',
      zh: 'Koko 把球带回来了，看起来特别骄傲。',
    },
    failText: {
      en: 'Koko still had fun. A cleaner whistle rhythm will help next time.',
      zh: 'Koko 玩得很开心，下次吹口哨节奏更稳会更好。',
    },
    actionLabel: { en: 'Whistle', zh: '吹口哨' },
    durationSeconds: 28,
    targetScore: 16,
    reward_config: {
      mood: 6,
      intimacy: 5,
      coins: 4,
      energy: -3,
      scoreMoodStep: 4,
      scoreIntimacyStep: 6,
      scoreCoinStep: 6,
      maxBonusMood: 8,
      maxBonusIntimacy: 6,
      maxBonusCoins: 8,
    },
    animation_state: 'idle',
    scene_config: {
      scene: 'grass',
      backgroundClass: 'mini-game-stage--catch',
      petPlacement: 'roaming',
      props: ['grass', 'ball', 'hardware-portal'],
    },
  },
  bubble: {
    game_id: 'bubble',
    title: { en: 'Bubble Pop', zh: '戳泡泡' },
    tabLabel: { en: 'Bubbles', zh: '泡泡' },
    goal: { en: 'Pop 18 bubbles', zh: '戳破 18 个泡泡' },
    startText: {
      en: 'The bathroom is filling with bubbles. Koko is watching them rise.',
      zh: '浴室泡泡开始升起来，Koko 会盯着泡泡互动。',
    },
    runningText: {
      en: 'Pop bubbles in a row. Combos increase the final reward.',
      zh: '连续戳破泡泡，连击越高奖励越好。',
    },
    successText: {
      en: 'The bathroom sparkles and Koko is bouncing happily.',
      zh: '浴室变得亮晶晶，Koko 开心地跳起来。',
    },
    failText: {
      en: 'A few bubbles escaped, but Koko is already looking for the next one.',
      zh: '有些泡泡飞走了，但 Koko 已经在找下一颗。',
    },
    actionLabel: { en: 'Pop bubbles', zh: '戳泡泡' },
    durationSeconds: 22,
    targetScore: 18,
    reward_config: {
      mood: 7,
      intimacy: 4,
      clean: 3,
      coins: 3,
      energy: -2,
      scoreMoodStep: 5,
      scoreIntimacyStep: 8,
      scoreCoinStep: 6,
      maxBonusMood: 8,
      maxBonusIntimacy: 5,
      maxBonusCoins: 8,
    },
    animation_state: 'watching',
    scene_config: {
      scene: 'bathroom',
      backgroundClass: 'mini-game-stage--bubble',
      petPlacement: 'lower-center',
      props: ['tiles', 'tub', 'bubbles'],
    },
  },
  jumpRope: {
    game_id: 'jumpRope',
    title: { en: 'Jump Rope', zh: '跳绳游戏' },
    tabLabel: { en: 'Jump', zh: '跳绳' },
    goal: { en: 'Hit 20 rhythm points', zh: '踩准 20 个节奏点' },
    startText: {
      en: 'Koko is ready outdoors. Tap when the rope reaches the rhythm zone.',
      zh: 'Koko 在户外准备好了，绳子到节奏区时点击跳跃。',
    },
    runningText: {
      en: 'Keep the rhythm. A mistimed tap makes Koko tumble.',
      zh: '保持节奏，点早或点晚都会触发摔倒动作。',
    },
    successText: {
      en: 'Clean rhythm. Koko finished the rope set with bright eyes.',
      zh: '节奏很稳，Koko 亮着眼睛完成了这一组。',
    },
    failText: {
      en: 'Koko stumbled, shook it off, and wants another try soon.',
      zh: 'Koko 摔了一下又站起来了，等会儿还想再试。',
    },
    actionLabel: { en: 'Jump', zh: '跳跃' },
    durationSeconds: 24,
    targetScore: 20,
    reward_config: {
      mood: 5,
      intimacy: 5,
      coins: 4,
      energy: -5,
      scoreMoodStep: 5,
      scoreIntimacyStep: 6,
      scoreCoinStep: 7,
      maxBonusMood: 7,
      maxBonusIntimacy: 7,
      maxBonusCoins: 8,
    },
    animation_state: 'idle',
    scene_config: {
      scene: 'outdoor',
      backgroundClass: 'mini-game-stage--jump',
      petPlacement: 'center',
      props: ['rope', 'rhythm-zone', 'field'],
    },
  },
  hideSeek: {
    game_id: 'hideSeek',
    title: { en: 'Hide and Seek', zh: '捉迷藏' },
    tabLabel: { en: 'Seek', zh: '捉迷藏' },
    goal: { en: 'Find Koko 3 times', zh: '找到 Koko 3 次' },
    startText: {
      en: 'Koko will hide behind one of the park props. Tap a prop to search.',
      zh: 'Koko 会随机躲到物体后面，点击物体开始寻找。',
    },
    runningText: {
      en: 'Search the scene. Correct finds build exploration rewards.',
      zh: '探索场景，找对次数越多奖励越高。',
    },
    successText: {
      en: 'You found Koko. It popped out with a happy little spin.',
      zh: '你找到 Koko 了，它开心地转了一圈跳出来。',
    },
    failText: {
      en: 'Koko stayed hidden this round. Try reading the scene clues next time.',
      zh: '这轮 Koko 藏得很好，下次可以多看场景线索。',
    },
    actionLabel: { en: 'Search', zh: '寻找' },
    durationSeconds: 26,
    targetScore: 15,
    reward_config: {
      mood: 6,
      intimacy: 6,
      coins: 5,
      energy: -3,
      scoreMoodStep: 5,
      scoreIntimacyStep: 5,
      scoreCoinStep: 5,
      maxBonusMood: 7,
      maxBonusIntimacy: 8,
      maxBonusCoins: 9,
    },
    animation_state: 'hiding',
    scene_config: {
      scene: 'hideout',
      backgroundClass: 'mini-game-stage--hide',
      petPlacement: 'hidden',
      props: ['bench', 'shrub', 'box', 'curtain', 'mailbox', 'basket', 'tent', 'log', 'flower'],
    },
  },
}
